source 'https://rubygems.org'

gem 'rake'
gem 'opal',           :github => 'opal/opal', :ref => '85220f32136c74ac93f1cb721462324a3423cf44'
gem 'opal-jquery',    :github => 'opal/opal-jquery'
gem 'vienna',         :github => 'opal/vienna', :ref => '593335cbd7fb99ce471fa720e9b9c849d99b8dda'
gem 'opal-haml',      :github => 'opal/opal-haml'
gem 'opal-rspec',     '0.3.0.beta2'
gem 'react.rb', :path => "../.."
gem 'thin'
gem 'react-source'
